version: "2.1"
services:
   web:
       image: nginx:latest
       ports:
          - "8111:80"
       volumes:
          - .:/app
          - ./site.conf:/etc/nginx/conf.d/default.conf
   php:
      image: php:7-fpm
      volumes:
          - .:/app
